<a href="https://colab.research.google.com/github/gurudattamanpreet/Practice/blob/main/PredCatch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
import gdown
url = 'https://drive.google.com/uc?id=1DCvwhFPMfKJUN3Rg3HMj9DoYgz3mIgWC'
output = 'finance_data.zip'
gdown.download(url, output, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1DCvwhFPMfKJUN3Rg3HMj9DoYgz3mIgWC
From (redirected): https://drive.google.com/uc?id=1DCvwhFPMfKJUN3Rg3HMj9DoYgz3mIgWC&confirm=t&uuid=703161df-01c8-4d66-b00a-261d35017e0c
To: /content/finance_data.zip
100%|██████████| 40.0M/40.0M [00:00<00:00, 211MB/s]

'finance_data.zip'

In [3]:
import zipfile

with zipfile.ZipFile("finance_data.zip", 'r') as zip_ref:
    zip_ref.extractall("finance_data")

In [4]:
import os
import pandas as pd

# Step 1: Recursively find all CSVs
csv_files = []
for root, dirs, files in os.walk("finance_data"):
    for file in files:
        if file.endswith(".csv"):
            full_path = os.path.join(root, file)
            csv_files.append(full_path)

# Step 2: Sort files for consistent naming
csv_files.sort()

# Step 3: Load into df1, df2, ..., df6
for i, path in enumerate(csv_files, start=1):
    globals()[f'df{i}'] = pd.read_csv(path)
    print(f"✅ Loaded {path} → df{i}")

✅ Loaded finance_data/Capston project finance dept/Geo_scores.csv → df1
✅ Loaded finance_data/Capston project finance dept/Lambda_wts.csv → df2
✅ Loaded finance_data/Capston project finance dept/Qset_tats.csv → df3
✅ Loaded finance_data/Capston project finance dept/instance_scores.csv → df4
✅ Loaded finance_data/Capston project finance dept/test_share.csv → df5
✅ Loaded finance_data/Capston project finance dept/train.csv → df6

In [5]:
w=[df1,df2,df3,df4,df5,df6]
for i in w:
  print(i.shape,'\n')

(1424035, 2)

(1400, 2)

(1424035, 2)

(1424035, 2)

(56962, 27)

(227845, 28)

In [6]:
s=[df1,df2,df3,df4]
for i in s:
  print(i.columns.tolist())

['id', 'geo_score']
['Group', 'lambda_wt']
['id', 'qsets_normalized_tat']
['id', 'instance_scores']

In [7]:
merged1 = pd.merge(df1, df3, on='id', how='left')
merged = pd.merge(merged1, df4, on='id', how='left')

In [8]:
merged.shape

(35600875, 4)

In [9]:
merged.columns.tolist()

['id', 'geo_score', 'qsets_normalized_tat', 'instance_scores']

In [10]:
s0=[df1,df3,df4]
for i in s0:
  print(i.nunique(),'\n')

id           284807
geo_score     25523
dtype: int64

id                      284807
qsets_normalized_tat     24832
dtype: int64

id                 284807
instance_scores     11158
dtype: int64

In [11]:
s1=[df1,df3,df4]
for i in s1:
  print(i.duplicated(subset='id').sum(),'\n')

1139228

1139228

1139228

In [12]:
s2 = [df1, df3, df4]
for x, df in enumerate(s2):
    s2[x] = df.drop_duplicates(subset='id')
df1, df3, df4 = s2

In [13]:
s3=[df1,df3,df4]
for i in s3:
  print(i.shape,'\n')

(284807, 2)

(284807, 2)

(284807, 2)

In [14]:
df0=pd.merge(df1,df3,on='id')
merged=pd.merge(df0,df4, on='id')

In [15]:
merged.shape

(284807, 4)

In [16]:
df5.shape

(56962, 27)

In [17]:
df6.shape

(227845, 28)

In [18]:
df2.nunique()

Group        1400
lambda_wt    1400
dtype: int64

In [19]:
df5.shape

(56962, 27)

In [20]:
df6.shape

(227845, 28)

In [21]:
df6.columns

Index(['id', 'Group', 'Per1', 'Per2', 'Per3', 'Per4', 'Per5', 'Per6', 'Per7',
       'Per8', 'Per9', 'Dem1', 'Dem2', 'Dem3', 'Dem4', 'Dem5', 'Dem6', 'Dem7',
       'Dem8', 'Dem9', 'Cred1', 'Cred2', 'Cred3', 'Cred4', 'Cred5', 'Cred6',
       'Normalised_FNT', 'Target'],
      dtype='object')

In [22]:
df6['Target'].value_counts()

Target
0    227451
1       394
Name: count, dtype: int64

In [23]:
df5.columns

Index(['id', 'Group', 'Per1', 'Per2', 'Per3', 'Per4', 'Per5', 'Per6', 'Per7',
       'Per8', 'Per9', 'Dem1', 'Dem2', 'Dem3', 'Dem4', 'Dem5', 'Dem6', 'Dem7',
       'Dem8', 'Dem9', 'Cred1', 'Cred2', 'Cred3', 'Cred4', 'Cred5', 'Cred6',
       'Normalised_FNT'],
      dtype='object')

In [24]:
merged.columns

Index(['id', 'geo_score', 'qsets_normalized_tat', 'instance_scores'], dtype='object')

In [25]:
merged.shape

(284807, 4)

In [26]:
df5.shape

(56962, 27)

In [27]:
df2.columns

Index(['Group', 'lambda_wt'], dtype='object')

In [28]:
df7,df8=train_test_split(merged,test_size=0.2,random_state=1)

In [29]:
df6.shape

(227845, 28)

In [30]:
df7.shape

(227845, 4)

In [31]:
train1=pd.merge(df6,df7, on='id',how='left')
test1=pd.merge(df5,df8, on='id',how='left')

In [32]:
train1.shape

(227845, 31)

In [33]:
test1.shape

(56962, 30)

In [34]:
df9,df10=train_test_split(df2,test_size=0.2,random_state=1)

In [35]:
df9.shape

(1120, 2)

In [36]:
df9.nunique()

Group        1120
lambda_wt    1120
dtype: int64

In [37]:
df10.shape

(280, 2)

In [38]:
train_data=pd.merge(train1,df9,on='Group',how='left')
test_data=pd.merge(test1,df10,on='Group',how='left')

In [39]:
train_data.shape

(227845, 32)

In [40]:
test_data.shape

(56962, 31)

In [41]:
train_data.corr(numeric_only=True)['Target'].sort_values(ascending=False)

Target                  1.000000
Dem1                    0.150343
Per4                    0.133657
Per2                    0.093530
Dem6                    0.034915
Per8                    0.028638
Dem8                    0.026403
Dem7                    0.024294
Cred5                   0.011801
Cred6                   0.011039
Normalised_FNT          0.005469
Cred3                   0.004814
Dem9                    0.004088
Cred4                   0.003521
Cred1                  -0.003342
Dem2                   -0.004235
Dem3                   -0.004541
Cred2                  -0.006884
id                     -0.012034
qsets_normalized_tat   -0.032087
geo_score              -0.038291
Per6                   -0.044604
instance_scores        -0.081047
Per5                   -0.099358
Per9                   -0.099559
Per1                   -0.103576
Dem5                   -0.112257
Per7                   -0.187741
Dem4                   -0.195076
Per3                   -0.195099
lambda_wt              -0.308249
Name: Target, dtype: float64

In [42]:
train_data.nunique()

id                      227845
Group                     1301
Per1                      1778
Per2                      2319
Per3                      1469
Per4                      1292
Per5                      1881
Per6                      1477
Per7                      1901
Per8                      2047
Per9                      1203
Dem1                       910
Dem2                       762
Dem3                       747
Dem4                       983
Dem5                       838
Dem6                       817
Dem7                      1505
Dem8                      1537
Dem9                       812
Cred1                     1307
Cred2                      494
Cred3                      636
Cred4                      460
Cred5                      920
Cred6                      778
Normalised_FNT           29299
Target                       2
geo_score                13349
qsets_normalized_tat     13064
instance_scores           6148
lambda_wt                 1045
dtype: int64

In [43]:
train_data.describe().T

,count,mean,std,min,25%,50%,75%,max
id,227845.0,142404.076201,82170.248170,0.000000,71325.000000,142374.000000,213492.000000,284805.000000
Per1,227845.0,0.666006,0.654133,-18.136667,0.360000,0.670000,1.103333,1.483333
Per2,227845.0,0.667701,0.548305,-23.573333,0.470000,0.690000,0.933333,8.020000
Per3,227845.0,0.666315,0.506357,-15.443333,0.370000,0.726667,1.010000,3.793333
Per4,227845.0,0.666687,0.471956,-1.226667,0.383333,0.660000,0.913333,6.163333
Per5,227845.0,0.666723,0.461393,-37.246667,0.436667,0.650000,0.870000,12.266667
Per6,227845.0,0.667378,0.444573,-8.053333,0.410000,0.576667,0.800000,25.100000
Per7,227845.0,0.666934,0.415657,-13.853333,0.483333,0.680000,0.856667,40.863333
Per8,227845.0,0.666279,0.401546,-23.740000,0.596667,0.673333,0.776667,7.336667
Per9,227845.0,0.666688,0.366537,-3.810000,0.453333,0.650000,0.866667,5.863333
Dem1,227845.0,0.666576,0.340436,-0.893333,0.413333,0.656667,0.913333,4.673333
Dem2,227845.0,0.666329,0.332016,-1.263333,0.450000,0.663333,0.886667,3.043333
Dem3,227845.0,0.666380,0.305384,-0.833333,0.473333,0.683333,0.883333,3.626667
Dem4,227845.0,0.666871,0.292013,-3.853333,0.510000,0.690000,0.840000,6.440000
Dem5,227845.0,0.666518,0.279469,-2.500000,0.500000,0.666667,0.833333,2.080000
Dem6,227845.0,0.666748,0.271590,-0.976667,0.513333,0.666667,0.820000,2.530000
Dem7,227845.0,0.666394,0.257631,-17.500000,0.596667,0.646667,0.710000,9.413333
Dem8,227845.0,0.666540,0.244423,-10.943333,0.590000,0.656667,0.730000,9.733333
Dem9,227845.0,0.666535,0.241902,-2.296667,0.486667,0.670000,0.843333,4.166667
Cred1,227845.0,0.666684,0.207575,-14.270000,0.613333,0.663333,0.716667,8.176667
Cred2,227845.0,0.666264,0.202204,-0.280000,0.546667,0.680000,0.813333,2.193333
Cred3,227845.0,0.666755,0.174204,-2.766667,0.560000,0.673333,0.783333,3.173333
Cred4,227845.0,0.666878,0.160803,-0.080000,0.556667,0.650000,0.746667,1.840000
Cred5,227845.0,0.666566,0.135762,-6.856667,0.643333,0.666667,0.696667,11.203333
Cred6,227845.0,0.666776,0.111612,-4.476667,0.650000,0.670000,0.693333,11.950000
Normalised_FNT,227845.0,-227.954170,61.951661,-250.000000,-248.617500,-244.510000,-230.750000,6172.790000
Target,227845.0,0.001729,0.041548,0.000000,0.000000,0.000000,0.000000,1.000000
geo_score,173142.0,0.028087,7.808718,-99.700000,-5.850000,0.340000,5.860000,44.860000
qsets_normalized_tat,169009.0,-0.011101,7.702537,-113.210000,-5.860000,-0.130000,5.860000,49.580000
instance_scores,182226.0,0.003475,2.566380,-123.190000,-0.640000,-0.040000,0.580000,74.050000
lambda_wt,186699.0,-0.004279,0.949413,-18.820000,-0.410000,0.050000,0.480000,10.530000

    In this we have target column which is only in the train_data
    the test data donot have any target column because that will be used at the time of deployment
    hence, we will split the train data into train and validation data so that we can check our model is working fine

In [44]:
train_data.drop(['id'],axis=1,inplace=True)
test_data.drop(['id'],axis=1,inplace=True)

In [45]:
X=train_data.drop(['Target'],axis=1)
y=train_data['Target']

In [46]:
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=1,stratify=y)

In [47]:
X_train.shape

(182276, 30)

In [48]:
X_train.columns

Index(['Group', 'Per1', 'Per2', 'Per3', 'Per4', 'Per5', 'Per6', 'Per7', 'Per8',
       'Per9', 'Dem1', 'Dem2', 'Dem3', 'Dem4', 'Dem5', 'Dem6', 'Dem7', 'Dem8',
       'Dem9', 'Cred1', 'Cred2', 'Cred3', 'Cred4', 'Cred5', 'Cred6',
       'Normalised_FNT', 'geo_score', 'qsets_normalized_tat',
       'instance_scores', 'lambda_wt'],
      dtype='object')

In [49]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [50]:
from sklearn.pipeline import Pipeline as Skpipeline
from imblearn.pipeline import Pipeline as Imbpipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score, StratifiedKFold

    2. MLOps & Production Perspective
    Manual Approach Problems: smote outside pipeline

    ❌ Multiple steps to manage
    ❌ Data leakage risk
    ❌ Hard to deploy
    ❌ Difficult to version control
    ❌ Error-prone in production

    Pipeline Approach Benefits: smote inside pipeline
    Industry Approach:

    ✅ Single object to deploy
    ✅ No data leakage (automatic train/test split handling)
    ✅ Easy to serialize (joblib.dump)
    ✅ Reproducible
    ✅ CI/CD friendly

In [51]:
num_cols = X_train.select_dtypes('number').columns.tolist()
cat_cols = X_train.select_dtypes('object').columns.tolist()

num_pipeline = Skpipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipeline = Skpipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encode', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
], remainder='passthrough')

In [52]:
pipe=Imbpipeline([
    ('preprocessor',preprocessor),
    ('pca',PCA(n_components=10)),
    ('smote',SMOTE(sampling_strategy=0.1)),
    ('model',LogisticRegression())])

In [53]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Per1', 'Per2', 'Per3',
                                                   'Per4', 'Per5', 'Per6',
                                                   'Per7', 'Per8', 'Per9',
                                                   'Dem1', 'Dem2', 'Dem3',
                                                   'Dem4', 'Dem5', 'Dem6',
                                                   'Dem7', 'Dem8', 'Dem9',
                                                   'Cred1', 'Cred2', 'Cred3',
                                                   'Cred4', 'Cred5...
                                                   'Normalised_FNT',
                                                   'geo_score',
                                                   'qsets_normalized_tat',
                                                   'instance_scores',
                                                   'lambda_wt']),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encode',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Group'])])),
                ('pca', PCA(n_components=10)),
                ('smote', SMOTE(sampling_strategy=0.1)),
                ('model', LogisticRegression())])

In [54]:
y_test_pred = pipe.predict(X_val)
print(classification_report(y_val, y_test_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.27      0.72      0.40        79

    accuracy                           1.00     45569
   macro avg       0.64      0.86      0.70     45569
weighted avg       1.00      1.00      1.00     45569

In [55]:
accuracy_score(y_val,y_test_pred)

0.9962035594373367

In [56]:
cv_scores=cross_val_score(pipe, X_train, y_train,
                           cv=StratifiedKFold(n_splits=5),
                           scoring='accuracy')

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [57]:
print(f"CV Mean: {cv_scores.mean():.3f}")
print(f"CV Std: {cv_scores.std():.3f}")  # High std = overfitting sign

CV Mean: 0.996
CV Std: 0.001

    pipe.fit(X_train,y_train) se hamara model trained ho gya with SMOTE

    ab is balanced model jo train hua h uska effect test data pr kaisa aa rha h hum ye dekhte h
    ab humko iska direct effect validatation/test data pe dekhna hota h

Test Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.34      0.73      0.46        79

    accuracy                           1.00     45569
   macro avg       0.67      0.87      0.73     45569
weighted avg       1.00      1.00      1.00     45569

In [57]:
# accuracy_score(y_resampled, y_train_pred)

In [56]:
accuracy_score(y_val, y_test_pred)

0.9970155149333977

In [58]:
classifiers = [[RandomForestClassifier(),'Random Forest'],
               [KNeighborsClassifier(), 'K-Nearest Neighbours'],
               [SVC(),'SVC'],
               [DecisionTreeClassifier(),'Decision Tree Classifier'],
               [LogisticRegression(),'Logistic Regression']]

In [61]:
for classifier in classifiers:
    pipeline = Skpipeline(steps = [
               ('preprocessor', preprocessor)
              ,('classifier',classifier)
           ])
    model = pipe.fit(X_train, y_train)
    predictions = model.predict(X_val)
    print(classifier)
    print(classification_report(y_val, predictions))

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[RandomForestClassifier(), 'Random Forest']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.28      0.72      0.40        79

    accuracy                           1.00     45569
   macro avg       0.64      0.86      0.70     45569
weighted avg       1.00      1.00      1.00     45569

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[KNeighborsClassifier(), 'K-Nearest Neighbours']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.23      0.70      0.34        79

    accuracy                           1.00     45569
   macro avg       0.61      0.85      0.67     45569
weighted avg       1.00      1.00      1.00     45569

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[SVC(), 'SVC']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.35      0.71      0.47        79

    accuracy                           1.00     45569
   macro avg       0.68      0.85      0.74     45569
weighted avg       1.00      1.00      1.00     45569

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[DecisionTreeClassifier(), 'Decision Tree Classifier']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.26      0.73      0.38        79

    accuracy                           1.00     45569
   macro avg       0.63      0.87      0.69     45569
weighted avg       1.00      1.00      1.00     45569

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[LogisticRegression(), 'Logistic Regression']
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     45490
           1       0.30      0.73      0.42        79

    accuracy                           1.00     45569
   macro avg       0.65      0.87      0.71     45569
weighted avg       1.00      1.00      1.00     45569