<a href="https://colab.research.google.com/github/gurudattamanpreet/Practice/blob/main/Titanic5_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
from sklearn.utils import class_weight

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/gurudattamanpreet/datasets/refs/heads/main/Titanic.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
df.drop(['PassengerId','Ticket','Cabin','Name'],axis=1,inplace=True)

In [7]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [8]:
df.fillna({'Age':df['Age'].mean(),'Embarked':df['Embarked'].mode()[0]},inplace=True)

In [9]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [10]:
pd.DataFrame({'dtypes':df.dtypes,'unique_values':df.nunique()})

           dtypes  unique_values
Survived    int64              2
Pclass      int64              3
Sex        object              2
Age       float64             89
SibSp       int64              7
Parch       int64              7
Fare      float64            248
Embarked   object              3

In [11]:
df['Familysize']=df['SibSp']+df['Parch']+1
df['Alone']=(df['Familysize']==1).astype(int)
df['Fareperperson']=df['Fare']/df['Familysize']

In [12]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Familysize,Alone,Fareperperson
0,0,3,male,22.0,1,0,7.2500,S,2,0,3.62500
1,1,1,female,38.0,1,0,71.2833,C,2,0,35.64165
2,1,3,female,26.0,0,0,7.9250,S,1,1,7.92500
3,1,1,female,35.0,1,0,53.1000,S,2,0,26.55000
4,0,3,male,35.0,0,0,8.0500,S,1,1,8.05000

In [13]:
df.drop(['SibSp','Parch'],axis=1,inplace=True)

In [14]:
df.head()

,Survived,Pclass,Sex,Age,Fare,Embarked,Familysize,Alone,Fareperperson
0,0,3,male,22.0,7.2500,S,2,0,3.62500
1,1,1,female,38.0,71.2833,C,2,0,35.64165
2,1,3,female,26.0,7.9250,S,1,1,7.92500
3,1,1,female,35.0,53.1000,S,2,0,26.55000
4,0,3,male,35.0,8.0500,S,1,1,8.05000

In [15]:
df['Sex']=df['Sex'].map({'male':1,'female':0})

In [17]:
df=pd.get_dummies(df,columns=['Embarked'],drop_first=True)

In [18]:
df.head()

,Survived,Pclass,Sex,Age,Fare,Familysize,Alone,Fareperperson,Embarked_Q,Embarked_S
0,0,3,1,22.0,7.2500,2,0,3.62500,False,True
1,1,1,0,38.0,71.2833,2,0,35.64165,False,False
2,1,3,0,26.0,7.9250,1,1,7.92500,False,True
3,1,1,0,35.0,53.1000,2,0,26.55000,False,True
4,0,3,1,35.0,8.0500,1,1,8.05000,False,True

In [19]:
X=df.drop(['Survived'],axis=1)
y=df['Survived']

In [21]:
sc=StandardScaler()
X_Scaled=sc.fit_transform(X)

In [23]:
X_Scaled.shape

(891, 9)

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X_Scaled,y,test_size=0.2,random_state=1,stratify=y)

In [27]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # binary output

# Step 3: Compile and Train
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=16, validation_split=0.2)

# Step 4: Evaluate
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.6080 - loss: 0.6560 - val_accuracy: 0.7692 - val_loss: 0.5562
Epoch 2/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7936 - loss: 0.5242 - val_accuracy: 0.7762 - val_loss: 0.4837
Epoch 3/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8007 - loss: 0.4733 - val_accuracy: 0.7622 - val_loss: 0.4649
Epoch 4/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8213 - loss: 0.4213 - val_accuracy: 0.7692 - val_loss: 0.4715
Epoch 5/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7957 - loss: 0.4551 - val_accuracy: 0.7692 - val_loss: 0.4715
Epoch 6/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8159 - loss: 0.4250 - val_accuracy: 0.7762 - val_loss: 0.4762
Epoch 7/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8242 - loss: 0.4185 - val_accuracy: 0.7622 - val_loss: 0.4712
Epoch 8/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8019 - loss: 0.4469 - val_accuracy: 0.7762 - val_loss: 0.4744
Epoch 9/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8372 - loss: 0.3908 - val_accuracy: 0.7622 - val_loss: 0.4763
Epoch 10/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8041 - loss: 0.4181 - val_accuracy: 0.7622 - val_loss: 0.4758
Epoch 11/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3925 - val_accuracy: 0.7692 - val_loss: 0.4772
Epoch 12/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 0.4100 - val_accuracy: 0.7692 - val_loss: 0.4739
Epoch 13/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8366 - loss: 0.3802 - val_accuracy: 0.7622 - val_loss: 0.4810
Epoch 14/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4096 - val_accuracy: 0.7692 - val_loss: 0.4714
Epoch 15/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8325 - loss: 0.3936 - val_accuracy: 0.7692 - val_loss: 0.4711
Epoch 16/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8536 - loss: 0.3841 - val_accuracy: 0.7692 - val_loss: 0.4720
Epoch 17/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8261 - loss: 0.4192 - val_accuracy: 0.7762 - val_loss: 0.4698
Epoch 18/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8343 - loss: 0.3916 - val_accuracy: 0.7692 - val_loss: 0.4698
Epoch 19/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8400 - loss: 0.3785 - val_accuracy: 0.7692 - val_loss: 0.4756
Epoch 20/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8506 - loss: 0.3594 - val_accuracy: 0.7762 - val_loss: 0.4701
Epoch 21/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8584 - loss: 0.3809 - val_accuracy: 0.7762 - val_loss: 0.4722
Epoch 22/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8484 - loss: 0.3616 - val_accuracy: 0.7692 - val_loss: 0.4758
Epoch 23/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8444 - loss: 0.3935 - val_accuracy: 0.7692 - val_loss: 0.4709
Epoch 24/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8616 - loss: 0.3729 - val_accuracy: 0.7622 - val_loss: 0.4743
Epoch 25/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8605 - loss: 0.3579 - val_accuracy: 0.7692 - val_loss: 0.4678
Epoch 26/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8754 - loss: 0.3695 - val_accuracy: 0.7622 - val_loss: 0.4717
Epoch 27/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8443 - loss: 0.3636 - val_accuracy: 0.7692 - val_loss: 0.4750
Epoch 28/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8181 - loss: 0.4082 - val_accuracy: 0.7622 - val_loss: 0.4707
Epoch 29/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8217 - loss: 0.3785 - val_accuracy: 0.7552 - val_loss: 0.4756
Epoch 30/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8538 - loss: 0.3690 - val_accuracy: 0.7622 - val_loss: 0.4772
Epoch 31/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8406 - loss: 0.3794 - val_accuracy: 0.7622 - val_loss: 0.4782
Epoch 32/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3469 - val_accuracy: 0.7762 - val_loss: 0.4747
Epoch 33/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8509 - loss: 0.3532 - val_accuracy: 0.7622 - val_loss: 0.4816
Epoch 34/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8542 - loss: 0.3772 - val_accuracy: 0.7692 - val_loss: 0.4821
Epoch 35/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8488 - loss: 0.3834 - val_accuracy: 0.7692 - val_loss: 0.4831
Epoch 36/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8248 - loss: 0.3724 - val_accuracy: 0.7692 - val_loss: 0.4822
Epoch 37/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8632 - loss: 0.3435 - val_accuracy: 0.7692 - val_loss: 0.4819
Epoch 38/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8248 - loss: 0.3774 - val_accuracy: 0.7622 - val_loss: 0.4786
Epoch 39/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8147 - loss: 0.4070 - val_accuracy: 0.7622 - val_loss: 0.4833
Epoch 40/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8733 - loss: 0.3462 - val_accuracy: 0.7622 - val_loss: 0.4875
Epoch 41/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8482 - loss: 0.3985 - val_accuracy: 0.7622 - val_loss: 0.4787
Epoch 42/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8540 - loss: 0.3565 - val_accuracy: 0.7692 - val_loss: 0.4773
Epoch 43/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.3837 - val_accuracy: 0.7622 - val_loss: 0.4801
Epoch 44/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8325 - loss: 0.3889 - val_accuracy: 0.7622 - val_loss: 0.4813
Epoch 45/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8459 - loss: 0.3797 - val_accuracy: 0.7692 - val_loss: 0.4820
Epoch 46/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3559 - val_accuracy: 0.7552 - val_loss: 0.4822
Epoch 47/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8554 - loss: 0.3353 - val_accuracy: 0.7622 - val_loss: 0.4858
Epoch 48/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8511 - loss: 0.3638 - val_accuracy: 0.7552 - val_loss: 0.4890
Epoch 49/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8294 - loss: 0.3727 - val_accuracy: 0.7622 - val_loss: 0.4855
Epoch 50/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8397 - loss: 0.3719 - val_accuracy: 0.7622 - val_loss: 0.4855
Epoch 51/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8472 - loss: 0.3697 - val_accuracy: 0.7622 - val_loss: 0.4876
Epoch 52/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8621 - loss: 0.3392 - val_accuracy: 0.7622 - val_loss: 0.4898
Epoch 53/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8612 - loss: 0.3414 - val_accuracy: 0.7622 - val_loss: 0.4839
Epoch 54/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8377 - loss: 0.3600 - val_accuracy: 0.7692 - val_loss: 0.4850
Epoch 55/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8724 - loss: 0.3535 - val_accuracy: 0.7762 - val_loss: 0.4825
Epoch 56/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8277 - loss: 0.3846 - val_accuracy: 0.7692 - val_loss: 0.4935
Epoch 57/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8624 - loss: 0.3498 - val_accuracy: 0.7622 - val_loss: 0.4865
Epoch 58/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8650 - loss: 0.3428 - val_accuracy: 0.7622 - val_loss: 0.4916
Epoch 59/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8745 - loss: 0.3504 - val_accuracy: 0.7622 - val_loss: 0.4953
Epoch 60/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8596 - loss: 0.3236 - val_accuracy: 0.7552 - val_loss: 0.4899
Epoch 61/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8616 - loss: 0.3462 - val_accuracy: 0.7622 - val_loss: 0.4967
Epoch 62/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8461 - loss: 0.3632 - val_accuracy: 0.7622 - val_loss: 0.4907
Epoch 63/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8413 - loss: 0.3363 - val_accuracy: 0.7483 - val_loss: 0.4942
Epoch 64/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8485 - loss: 0.3639 - val_accuracy: 0.7762 - val_loss: 0.4926
Epoch 65/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8363 - loss: 0.3759 - val_accuracy: 0.7622 - val_loss: 0.4961
Epoch 66/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8150 - loss: 0.3868 - val_accuracy: 0.7552 - val_loss: 0.5002
Epoch 67/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8636 - loss: 0.3112 - val_accuracy: 0.7622 - val_loss: 0.4911
Epoch 68/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8478 - loss: 0.3538 - val_accuracy: 0.7622 - val_loss: 0.4898
Epoch 69/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8544 - loss: 0.3243 - val_accuracy: 0.7483 - val_loss: 0.4916
Epoch 70/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8557 - loss: 0.3228 - val_accuracy: 0.7762 - val_loss: 0.4903
Epoch 71/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8541 - loss: 0.3201 - val_accuracy: 0.7692 - val_loss: 0.4941
Epoch 72/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8462 - loss: 0.3340 - val_accuracy: 0.7832 - val_loss: 0.4929
Epoch 73/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8145 - loss: 0.4015 - val_accuracy: 0.7832 - val_loss: 0.4879
Epoch 74/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8520 - loss: 0.3676 - val_accuracy: 0.7762 - val_loss: 0.4896
Epoch 75/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8389 - loss: 0.3551 - val_accuracy: 0.7692 - val_loss: 0.4929
Epoch 76/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8538 - loss: 0.3282 - val_accuracy: 0.7692 - val_loss: 0.4969
Epoch 77/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8560 - loss: 0.3345 - val_accuracy: 0.7762 - val_loss: 0.4935
Epoch 78/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8435 - loss: 0.3780 - val_accuracy: 0.7832 - val_loss: 0.4916
Epoch 79/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8476 - loss: 0.3515 - val_accuracy: 0.7692 - val_loss: 0.4963
Epoch 80/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8392 - loss: 0.3409 - val_accuracy: 0.7622 - val_loss: 0.4951
Epoch 81/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8544 - loss: 0.3287 - val_accuracy: 0.7622 - val_loss: 0.4987
Epoch 82/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8519 - loss: 0.3510 - val_accuracy: 0.7692 - val_loss: 0.4911
Epoch 83/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8580 - loss: 0.3445 - val_accuracy: 0.7692 - val_loss: 0.4961
Epoch 84/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8619 - loss: 0.3437 - val_accuracy: 0.7692 - val_loss: 0.5025
Epoch 85/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8423 - loss: 0.3961 - val_accuracy: 0.7622 - val_loss: 0.5037
Epoch 86/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8398 - loss: 0.3654 - val_accuracy: 0.7692 - val_loss: 0.5053
Epoch 87/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8706 - loss: 0.3146 - val_accuracy: 0.7552 - val_loss: 0.5000
Epoch 88/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8479 - loss: 0.3380 - val_accuracy: 0.7692 - val_loss: 0.5011
Epoch 89/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8678 - loss: 0.3471 - val_accuracy: 0.7762 - val_loss: 0.5044
Epoch 90/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8653 - loss: 0.3166 - val_accuracy: 0.7832 - val_loss: 0.5037
Epoch 91/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8524 - loss: 0.3681 - val_accuracy: 0.7762 - val_loss: 0.5058
Epoch 92/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8407 - loss: 0.3576 - val_accuracy: 0.7762 - val_loss: 0.5037
Epoch 93/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8464 - loss: 0.3237 - val_accuracy: 0.7692 - val_loss: 0.5070
Epoch 94/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8554 - loss: 0.3683 - val_accuracy: 0.7692 - val_loss: 0.5005
Epoch 95/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8564 - loss: 0.3196 - val_accuracy: 0.7832 - val_loss: 0.5062
Epoch 96/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8231 - loss: 0.3484 - val_accuracy: 0.7762 - val_loss: 0.5048
Epoch 97/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8688 - loss: 0.3292 - val_accuracy: 0.7552 - val_loss: 0.5069
Epoch 98/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8561 - loss: 0.3157 - val_accuracy: 0.7832 - val_loss: 0.5081
Epoch 99/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8517 - loss: 0.3347 - val_accuracy: 0.7622 - val_loss: 0.5068
Epoch 100/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8391 - loss: 0.3699 - val_accuracy: 0.7762 - val_loss: 0.5035
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8231 - loss: 0.4760
Test Accuracy: 0.832402229309082

In [28]:
from sklearn.metrics import recall_score

# Step 1: Get predicted labels (0 or 1)
y_pred_test = (model.predict(X_test) > 0.5).astype("int32")  # threshold 0.5 by default

# Step 2: Compute recall
recall = recall_score(y_test, y_pred_test)
print("Recall (Test):", recall)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Recall (Test): 0.7246376811594203

In [37]:
from sklearn.utils import class_weight
import numpy as np

# Calculate class weights
class_weights = class_weight.compute_class_weight(class_weight='balanced',
                                                  classes=np.unique(y_train),
                                                  y=y_train)

# Convert to dict
class_weight_dict = dict(zip(np.unique(y_train), class_weights))

In [38]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.4),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(1, activation='sigmoid'),
])

model.compile(optimizer='adam', loss='binary_crossentropy',
              metrics=['accuracy', tf.keras.metrics.Recall()])

callbacks = [
    EarlyStopping(monitor='val_recall', patience=10, mode='max', restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_recall', factor=0.5, patience=5, mode='max')
]

model.fit(X_train, y_train,
          epochs=200, batch_size=16,
          validation_split=0.2,
          class_weight=class_weight_dict,
          callbacks=callbacks)

Epoch 1/200

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

36/36 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.4836 - loss: 0.9254 - recall_3: 0.4985 - val_accuracy: 0.7413 - val_loss: 0.6480 - val_recall_3: 0.7447 - learning_rate: 0.0010
Epoch 2/200
31/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6558 - loss: 0.7261 - recall_3: 0.6606

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_recall` which is not available. Available metrics are: accuracy,loss,recall_3,val_accuracy,val_loss,val_recall_3
  current = self.get_monitor_value(logs)
/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/callback_list.py:145: UserWarning: Learning rate reduction is conditioned on metric `val_recall` which is not available. Available metrics are: accuracy,loss,recall_3,val_accuracy,val_loss,val_recall_3,learning_rate.
  callback.on_epoch_end(epoch, logs)

36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6599 - loss: 0.7197 - recall_3: 0.6667 - val_accuracy: 0.7692 - val_loss: 0.6203 - val_recall_3: 0.7872 - learning_rate: 0.0010
Epoch 3/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6881 - loss: 0.6177 - recall_3: 0.6975 - val_accuracy: 0.7692 - val_loss: 0.5923 - val_recall_3: 0.7660 - learning_rate: 0.0010
Epoch 4/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7148 - loss: 0.6144 - recall_3: 0.7129 - val_accuracy: 0.7692 - val_loss: 0.5710 - val_recall_3: 0.7660 - learning_rate: 0.0010
Epoch 5/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7357 - loss: 0.5344 - recall_3: 0.7494 - val_accuracy: 0.7622 - val_loss: 0.5487 - val_recall_3: 0.7660 - learning_rate: 0.0010
Epoch 6/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7772 - loss: 0.5003 - recall_3: 0.7973 - val_accuracy: 0.7552 - val_loss: 0.5415 - val_recall_3: 0.7660 - learning_rate: 0.0010
Epoch 7/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7546 - loss: 0.5547 - recall_3: 0.7615 - val_accuracy: 0.7692 - val_loss: 0.5360 - val_recall_3: 0.7234 - learning_rate: 0.0010
Epoch 8/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7816 - loss: 0.5057 - recall_3: 0.7725 - val_accuracy: 0.7552 - val_loss: 0.5340 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 9/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7983 - loss: 0.4809 - recall_3: 0.8392 - val_accuracy: 0.7692 - val_loss: 0.5253 - val_recall_3: 0.7234 - learning_rate: 0.0010
Epoch 10/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7535 - loss: 0.5095 - recall_3: 0.7371 - val_accuracy: 0.7552 - val_loss: 0.5230 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 11/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7688 - loss: 0.5215 - recall_3: 0.7724 - val_accuracy: 0.7552 - val_loss: 0.5228 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 12/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7371 - loss: 0.5550 - recall_3: 0.7344 - val_accuracy: 0.7622 - val_loss: 0.5204 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 13/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7669 - loss: 0.5323 - recall_3: 0.7575 - val_accuracy: 0.7692 - val_loss: 0.5146 - val_recall_3: 0.7234 - learning_rate: 0.0010
Epoch 14/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8145 - loss: 0.4057 - recall_3: 0.8197 - val_accuracy: 0.7692 - val_loss: 0.5158 - val_recall_3: 0.7021 - learning_rate: 0.0010
Epoch 15/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4780 - recall_3: 0.8068 - val_accuracy: 0.7622 - val_loss: 0.5115 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 16/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8060 - loss: 0.4589 - recall_3: 0.8064 - val_accuracy: 0.7692 - val_loss: 0.5123 - val_recall_3: 0.7021 - learning_rate: 0.0010
Epoch 17/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7937 - loss: 0.4687 - recall_3: 0.7714 - val_accuracy: 0.7552 - val_loss: 0.5108 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 18/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7823 - loss: 0.5139 - recall_3: 0.7509 - val_accuracy: 0.7552 - val_loss: 0.5099 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 19/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7493 - loss: 0.5429 - recall_3: 0.6966 - val_accuracy: 0.7552 - val_loss: 0.5130 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 20/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7865 - loss: 0.5543 - recall_3: 0.7553 - val_accuracy: 0.7552 - val_loss: 0.5102 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 21/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7912 - loss: 0.4748 - recall_3: 0.7762 - val_accuracy: 0.7552 - val_loss: 0.5064 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 22/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7799 - loss: 0.4858 - recall_3: 0.7137 - val_accuracy: 0.7552 - val_loss: 0.5053 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 23/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8022 - loss: 0.4863 - recall_3: 0.7695 - val_accuracy: 0.7552 - val_loss: 0.5041 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 24/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7934 - loss: 0.4850 - recall_3: 0.7857 - val_accuracy: 0.7622 - val_loss: 0.5016 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 25/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7760 - loss: 0.4857 - recall_3: 0.7324 - val_accuracy: 0.7552 - val_loss: 0.5038 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 26/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8047 - loss: 0.4855 - recall_3: 0.8108 - val_accuracy: 0.7692 - val_loss: 0.5005 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 27/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7966 - loss: 0.4416 - recall_3: 0.7623 - val_accuracy: 0.7622 - val_loss: 0.5022 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 28/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7928 - loss: 0.5011 - recall_3: 0.7887 - val_accuracy: 0.7552 - val_loss: 0.5058 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 29/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8091 - loss: 0.4499 - recall_3: 0.7778 - val_accuracy: 0.7552 - val_loss: 0.5021 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 30/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7977 - loss: 0.4484 - recall_3: 0.8128 - val_accuracy: 0.7552 - val_loss: 0.5032 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 31/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7998 - loss: 0.4529 - recall_3: 0.7747 - val_accuracy: 0.7692 - val_loss: 0.5061 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 32/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7867 - loss: 0.4727 - recall_3: 0.7498 - val_accuracy: 0.7692 - val_loss: 0.5047 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 33/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7808 - loss: 0.5191 - recall_3: 0.7846 - val_accuracy: 0.7692 - val_loss: 0.5025 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 34/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7717 - loss: 0.5007 - recall_3: 0.7461 - val_accuracy: 0.7552 - val_loss: 0.5049 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 35/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8085 - loss: 0.4429 - recall_3: 0.7676 - val_accuracy: 0.7552 - val_loss: 0.5055 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 36/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7774 - loss: 0.4754 - recall_3: 0.7672 - val_accuracy: 0.7552 - val_loss: 0.5101 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 37/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7860 - loss: 0.4764 - recall_3: 0.7742 - val_accuracy: 0.7413 - val_loss: 0.5091 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 38/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8023 - loss: 0.4447 - recall_3: 0.7864 - val_accuracy: 0.7483 - val_loss: 0.5133 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 39/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7550 - loss: 0.5238 - recall_3: 0.7279 - val_accuracy: 0.7413 - val_loss: 0.5028 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 40/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8486 - loss: 0.3917 - recall_3: 0.8487 - val_accuracy: 0.7413 - val_loss: 0.5019 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 41/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8283 - loss: 0.4002 - recall_3: 0.8096 - val_accuracy: 0.7552 - val_loss: 0.4999 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 42/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8115 - loss: 0.4499 - recall_3: 0.8217 - val_accuracy: 0.7483 - val_loss: 0.4986 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 43/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8259 - loss: 0.4408 - recall_3: 0.8245 - val_accuracy: 0.7483 - val_loss: 0.4957 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 44/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7684 - loss: 0.5019 - recall_3: 0.7364 - val_accuracy: 0.7413 - val_loss: 0.4989 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 45/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8012 - loss: 0.4358 - recall_3: 0.7842 - val_accuracy: 0.7483 - val_loss: 0.4983 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 46/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7840 - loss: 0.4531 - recall_3: 0.7988 - val_accuracy: 0.7413 - val_loss: 0.5007 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 47/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8119 - loss: 0.4502 - recall_3: 0.8091 - val_accuracy: 0.7483 - val_loss: 0.4998 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 48/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8247 - loss: 0.3967 - recall_3: 0.8095 - val_accuracy: 0.7343 - val_loss: 0.5039 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 49/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.4136 - recall_3: 0.8136 - val_accuracy: 0.7343 - val_loss: 0.4978 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 50/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8061 - loss: 0.4939 - recall_3: 0.7532 - val_accuracy: 0.7413 - val_loss: 0.4963 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 51/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8214 - loss: 0.4625 - recall_3: 0.7722 - val_accuracy: 0.7413 - val_loss: 0.4956 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 52/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8005 - loss: 0.4626 - recall_3: 0.7871 - val_accuracy: 0.7413 - val_loss: 0.4926 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 53/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8129 - loss: 0.4439 - recall_3: 0.7979 - val_accuracy: 0.7413 - val_loss: 0.4915 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 54/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8096 - loss: 0.4677 - recall_3: 0.7604 - val_accuracy: 0.7413 - val_loss: 0.4905 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 55/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7957 - loss: 0.4966 - recall_3: 0.7630 - val_accuracy: 0.7413 - val_loss: 0.4903 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 56/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8204 - loss: 0.3964 - recall_3: 0.7845 - val_accuracy: 0.7413 - val_loss: 0.4902 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 57/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8224 - loss: 0.4101 - recall_3: 0.7999 - val_accuracy: 0.7413 - val_loss: 0.4934 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 58/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8055 - loss: 0.4307 - recall_3: 0.7643 - val_accuracy: 0.7413 - val_loss: 0.4931 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 59/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7835 - loss: 0.5150 - recall_3: 0.7348 - val_accuracy: 0.7552 - val_loss: 0.4948 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 60/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8133 - loss: 0.4341 - recall_3: 0.7829 - val_accuracy: 0.7413 - val_loss: 0.4967 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 61/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8372 - loss: 0.3831 - recall_3: 0.8183 - val_accuracy: 0.7413 - val_loss: 0.4959 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 62/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7925 - loss: 0.4534 - recall_3: 0.7520 - val_accuracy: 0.7413 - val_loss: 0.4891 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 63/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8321 - loss: 0.4195 - recall_3: 0.8228 - val_accuracy: 0.7413 - val_loss: 0.4917 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 64/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8219 - loss: 0.4620 - recall_3: 0.7624 - val_accuracy: 0.7413 - val_loss: 0.4945 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 65/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.4118 - recall_3: 0.7807 - val_accuracy: 0.7483 - val_loss: 0.4956 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 66/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8305 - loss: 0.4028 - recall_3: 0.8121 - val_accuracy: 0.7413 - val_loss: 0.5006 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 67/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8086 - loss: 0.4019 - recall_3: 0.7740 - val_accuracy: 0.7483 - val_loss: 0.4960 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 68/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4586 - recall_3: 0.7520 - val_accuracy: 0.7483 - val_loss: 0.4943 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 69/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8507 - loss: 0.3867 - recall_3: 0.8354 - val_accuracy: 0.7483 - val_loss: 0.5030 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 70/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7967 - loss: 0.4337 - recall_3: 0.7992 - val_accuracy: 0.7483 - val_loss: 0.4953 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 71/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8399 - loss: 0.4392 - recall_3: 0.7790 - val_accuracy: 0.7483 - val_loss: 0.4966 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 72/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8010 - loss: 0.4585 - recall_3: 0.7328 - val_accuracy: 0.7483 - val_loss: 0.4948 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 73/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8345 - loss: 0.3997 - recall_3: 0.8272 - val_accuracy: 0.7483 - val_loss: 0.4978 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 74/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8260 - loss: 0.4080 - recall_3: 0.7858 - val_accuracy: 0.7413 - val_loss: 0.4979 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 75/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.4393 - recall_3: 0.8164 - val_accuracy: 0.7343 - val_loss: 0.4972 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 76/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8093 - loss: 0.4218 - recall_3: 0.7732 - val_accuracy: 0.7483 - val_loss: 0.5029 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 77/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8169 - loss: 0.3816 - recall_3: 0.7464 - val_accuracy: 0.7622 - val_loss: 0.5044 - val_recall_3: 0.7021 - learning_rate: 0.0010
Epoch 78/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8087 - loss: 0.4487 - recall_3: 0.7645 - val_accuracy: 0.7552 - val_loss: 0.5032 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 79/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7934 - loss: 0.4555 - recall_3: 0.8099 - val_accuracy: 0.7483 - val_loss: 0.5008 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 80/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7991 - loss: 0.4155 - recall_3: 0.8123 - val_accuracy: 0.7483 - val_loss: 0.5057 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 81/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8465 - loss: 0.3846 - recall_3: 0.8296 - val_accuracy: 0.7552 - val_loss: 0.5056 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 82/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8376 - loss: 0.4114 - recall_3: 0.7858 - val_accuracy: 0.7552 - val_loss: 0.5056 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 83/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8203 - loss: 0.4316 - recall_3: 0.7848 - val_accuracy: 0.7483 - val_loss: 0.4953 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 84/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8499 - loss: 0.3877 - recall_3: 0.8301 - val_accuracy: 0.7552 - val_loss: 0.4949 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 85/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8011 - loss: 0.3995 - recall_3: 0.8080 - val_accuracy: 0.7483 - val_loss: 0.4988 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 86/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8099 - loss: 0.4199 - recall_3: 0.8093 - val_accuracy: 0.7343 - val_loss: 0.4995 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 87/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8327 - loss: 0.4031 - recall_3: 0.8434 - val_accuracy: 0.7483 - val_loss: 0.5050 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 88/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7819 - loss: 0.4184 - recall_3: 0.8144 - val_accuracy: 0.7413 - val_loss: 0.5049 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 89/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8237 - loss: 0.4220 - recall_3: 0.7770 - val_accuracy: 0.7552 - val_loss: 0.5034 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 90/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8507 - loss: 0.4021 - recall_3: 0.8291 - val_accuracy: 0.7413 - val_loss: 0.4967 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 91/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8365 - loss: 0.4004 - recall_3: 0.8388 - val_accuracy: 0.7552 - val_loss: 0.5014 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 92/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8098 - loss: 0.4350 - recall_3: 0.7830 - val_accuracy: 0.7483 - val_loss: 0.5033 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 93/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8314 - loss: 0.4154 - recall_3: 0.8012 - val_accuracy: 0.7552 - val_loss: 0.4980 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 94/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4192 - recall_3: 0.7574 - val_accuracy: 0.7622 - val_loss: 0.5056 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 95/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8036 - loss: 0.4330 - recall_3: 0.7618 - val_accuracy: 0.7413 - val_loss: 0.5074 - val_recall_3: 0.6383 - learning_rate: 0.0010
Epoch 96/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8378 - loss: 0.4129 - recall_3: 0.7999 - val_accuracy: 0.7552 - val_loss: 0.5091 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 97/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8254 - loss: 0.4318 - recall_3: 0.7937 - val_accuracy: 0.7552 - val_loss: 0.5112 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 98/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8267 - loss: 0.4226 - recall_3: 0.7692 - val_accuracy: 0.7552 - val_loss: 0.5090 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 99/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7974 - loss: 0.5137 - recall_3: 0.7691 - val_accuracy: 0.7483 - val_loss: 0.5034 - val_recall_3: 0.6596 - learning_rate: 0.0010
Epoch 100/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8154 - loss: 0.4332 - recall_3: 0.7773 - val_accuracy: 0.7483 - val_loss: 0.5041 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 101/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8132 - loss: 0.4343 - recall_3: 0.7971 - val_accuracy: 0.7483 - val_loss: 0.5013 - val_recall_3: 0.6809 - learning_rate: 0.0010
Epoch 102/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8065 - loss: 0.4318 - recall_3: 0.7581 - val_accuracy: 0.7552 - val_loss: 0.5072 - val_recall_3: 0.7021 - learning_rate: 0.0010
Epoch 103/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8092 - loss: 0.3895 - recall_3: 0.7826 - val_accuracy: 0.7552 - val_loss: 0.5099 - val_recall_3: 0.7021 - learning_rate: 0.0010
Epoch 104/200
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8354 - loss: 0.3815 - recall_3: 0.8374 - val_accuracy: 0.7552 - val_loss: 0.5120 - val_recall_3: 0.7021 - learning_rate: 0.0010
Epoch 105/200

In [39]:
from sklearn.metrics import classification_report

y_probs = model.predict(X_test)
y_pred = (y_probs > 0.5).astype("int32")

print(classification_report(y_test, y_pred))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       110
           1       0.75      0.81      0.78        69

    accuracy                           0.82       179
   macro avg       0.81      0.82      0.81       179
weighted avg       0.83      0.82      0.82       179

In [40]:
y_probs = model.predict(X_train)
y_pred = (y_probs > 0.5).astype("int32")

print(classification_report(y_train, y_pred))

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
              precision    recall  f1-score   support

           0       0.90      0.83      0.86       439
           1       0.76      0.85      0.80       273

    accuracy                           0.84       712
   macro avg       0.83      0.84      0.83       712
weighted avg       0.85      0.84      0.84       712

In [ ]:
accuracy_sc