<a href="https://colab.research.google.com/github/gurudattamanpreet/Practice/blob/main/usedcars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, OLS
from sklearn.model_selection import train_test_split, cross_val_score

ImportError: cannot import name 'OLS' from 'sklearn.metrics' (/usr/local/lib/python3.11/dist-packages/sklearn/metrics/__init__.py)

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gurudattamanpreet/datasets/refs/heads/main/usedcarsdata.csv')

In [3]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,5.51,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,16.06,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,11.27,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,53.14,17.74

In [4]:
df.shape

(7253, 14)

In [5]:
df.dtypes

S.No.                  int64
Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price            float64
Price                float64
dtype: object

In [6]:
pd.DataFrame({'datatypes':df.dtypes,'unique_count':df.nunique()})

                  datatypes  unique_count
S.No.                 int64          7253
Name                 object          2041
Location             object            11
Year                  int64            23
Kilometers_Driven     int64          3660
Fuel_Type            object             5
Transmission         object             2
Owner_Type           object             4
Mileage              object           450
Engine               object           150
Power                object           385
Seats               float64             9
New_Price           float64           643
Price               float64          1373

In [7]:
df.drop(['S.No.'],axis=1,inplace=True)

In [8]:
pd.DataFrame({'datatypes':df.dtypes,'unique_count':df.nunique()})

                  datatypes  unique_count
Name                 object          2041
Location             object            11
Year                  int64            23
Kilometers_Driven     int64          3660
Fuel_Type            object             5
Transmission         object             2
Owner_Type           object             4
Mileage              object           450
Engine               object           150
Power                object           385
Seats               float64             9
New_Price           float64           643
Price               float64          1373

In [9]:
df.select_dtypes(include=['int64','float64']).nunique()

Year                   23
Kilometers_Driven    3660
Seats                   9
New_Price             643
Price                1373
dtype: int64

In [10]:
df.select_dtypes(include=['object']).nunique()

Name            2041
Location          11
Fuel_Type          5
Transmission       2
Owner_Type         4
Mileage          450
Engine           150
Power            385
dtype: int64

In [11]:
df['Name']

0                                  Maruti Wagon R LXI CNG
1                        Hyundai Creta 1.6 CRDi SX Option
2                                            Honda Jazz V
3                                       Maruti Ertiga VDI
4                         Audi A4 New 2.0 TDI Multitronic
                              ...
7248                    Volkswagen Vento Diesel Trendline
7249                               Volkswagen Polo GT TSI
7250                               Nissan Micra Diesel XV
7251                               Volkswagen Polo GT TSI
7252    Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...
Name: Name, Length: 7253, dtype: object

    here we can see that brand name of each car is given

In [12]:
df['Brand']=df['Name'].str.split().str[0]

In [13]:
df['Brand'].nunique()

33

In [14]:
df['Model']=df['Name'].str.split().str[1]

In [15]:
df['Model'].nunique()

219

    analysing all object values one by one

In [16]:
s=['Location','Fuel_Type','Transmission','Owner_Type']
for i in s:
  print(df[i].value_counts(),'\n')

Location
Mumbai        949
Hyderabad     876
Coimbatore    772
Kochi         772
Pune          765
Delhi         660
Kolkata       654
Chennai       591
Jaipur        499
Bangalore     440
Ahmedabad     275
Name: count, dtype: int64

Fuel_Type
Diesel      3852
Petrol      3325
CNG           62
LPG           12
Electric       2
Name: count, dtype: int64

Transmission
Manual       5204
Automatic    2049
Name: count, dtype: int64

Owner_Type
First             5952
Second            1152
Third              137
Fourth & Above      12
Name: count, dtype: int64

In [17]:
w=['Mileage','Engine','Power']
for i in w:
  print(df[i].head(5),'\n')

0    26.6 km/kg
1    19.67 kmpl
2     18.2 kmpl
3    20.77 kmpl
4     15.2 kmpl
Name: Mileage, dtype: object

0     998 CC
1    1582 CC
2    1199 CC
3    1248 CC
4    1968 CC
Name: Engine, dtype: object

0    58.16 bhp
1    126.2 bhp
2     88.7 bhp
3    88.76 bhp
4    140.8 bhp
Name: Power, dtype: object

    here we can see that mileage power and engine are written along with their units
    we need to seprate thier unit and values in different variables

In [18]:
df['mileage_num']=df['Mileage'].str.split().str[0].astype('float64')
df['mileage_unit']=df['Mileage'].str.split().str[1]
df['engine_num']=df['Engine'].str.split().str[0].astype('float64')
df['engine_unit']=df['Engine'].str.split().str[1]
df['power_num']=df['Power'].str.split().str[0].astype('float64')
df['power_unit']=df['Power'].str.split().str[1]

In [19]:
q=['mileage_unit','engine_unit','power_unit']
for i in q:
  print(df[i].value_counts(),'\n')

mileage_unit
kmpl     7177
km/kg      74
Name: count, dtype: int64

engine_unit
CC    7207
Name: count, dtype: int64

power_unit
bhp    7078
Name: count, dtype: int64

In [20]:
df.select_dtypes(include=['float64','int64']).nunique()

Year                   23
Kilometers_Driven    3660
Seats                   9
New_Price             643
Price                1373
mileage_num           438
engine_num            150
power_num             383
dtype: int64

In [21]:
df.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price            float64
Price                float64
Brand                 object
Model                 object
mileage_num          float64
mileage_unit          object
engine_num           float64
engine_unit           object
power_num            float64
power_unit            object
dtype: object

In [22]:
df.drop(['Name','Mileage','Engine','Power'],axis=1,inplace=True)

    we need to check extreme values in numeric attributes

In [23]:
df.sort_values(by='Kilometers_Driven',ascending=False).head(5)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
2328,Chennai,2017,6500000,Diesel,Automatic,First,5.0,55.07,65.0,BMW,X5,15.97,kmpl,2993.0,CC,258.00,bhp
340,Kolkata,2013,775000,Diesel,Automatic,First,5.0,25.83,7.5,Skoda,Octavia,19.30,kmpl,1968.0,CC,141.00,bhp
1860,Chennai,2013,720000,Diesel,Manual,First,5.0,13.23,5.9,Volkswagen,Vento,20.54,kmpl,1598.0,CC,103.60,bhp
358,Chennai,2009,620000,Petrol,Manual,First,5.0,10.25,2.7,Hyundai,i10,20.36,kmpl,1197.0,CC,78.90,bhp
2823,Chennai,2015,480000,Diesel,Automatic,First,5.0,10.15,13.0,Volkswagen,Jetta,16.96,kmpl,1968.0,CC,138.03,bhp

    here we can see that kilmoeters driven=6,50,000 it was purchased in the year of 2017,
    practically it is impossible to cover this much distance
    hence we will impute this value with NaN

In [24]:
df.loc[2328, "Kilometers_Driven"] = np.nan

In [25]:
df.sort_values(by='Kilometers_Driven',ascending=True).head(5)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
1361,Mumbai,2019,171.0,Petrol,Manual,First,5.0,4.36,3.60,Maruti,Alto,24.70,kmpl,796.0,CC,47.3,bhp
5606,Mumbai,2019,600.0,Petrol,Automatic,First,5.0,6.80,6.25,Maruti,Wagon,21.50,kmpl,1197.0,CC,81.8,bhp
2054,Mumbai,2017,1000.0,Petrol,Manual,First,5.0,7.87,6.36,Maruti,Ignis,20.89,kmpl,1197.0,CC,81.8,bhp
1161,Ahmedabad,2018,1000.0,Petrol,Automatic,First,5.0,7.15,6.85,Tata,Tigor,20.30,kmpl,1199.0,CC,84.0,bhp
6201,Kolkata,2019,1000.0,Petrol,Manual,First,5.0,3.99,NaN,Maruti,Alto,24.70,kmpl,796.0,CC,47.3,bhp

In [26]:
df.sort_values(by='Kilometers_Driven',ascending=True).head(5)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
1361,Mumbai,2019,171.0,Petrol,Manual,First,5.0,4.36,3.60,Maruti,Alto,24.70,kmpl,796.0,CC,47.3,bhp
5606,Mumbai,2019,600.0,Petrol,Automatic,First,5.0,6.80,6.25,Maruti,Wagon,21.50,kmpl,1197.0,CC,81.8,bhp
2054,Mumbai,2017,1000.0,Petrol,Manual,First,5.0,7.87,6.36,Maruti,Ignis,20.89,kmpl,1197.0,CC,81.8,bhp
1161,Ahmedabad,2018,1000.0,Petrol,Automatic,First,5.0,7.15,6.85,Tata,Tigor,20.30,kmpl,1199.0,CC,84.0,bhp
6201,Kolkata,2019,1000.0,Petrol,Manual,First,5.0,3.99,NaN,Maruti,Alto,24.70,kmpl,796.0,CC,47.3,bhp

In [27]:
df.select_dtypes(include=['float64','int64']).dtypes

Year                   int64
Kilometers_Driven    float64
Seats                float64
New_Price            float64
Price                float64
mileage_num          float64
engine_num           float64
power_num            float64
dtype: object

In [28]:
df.sort_values(by='Seats',ascending=True).head(5)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
3999,Hyderabad,2012,125000.0,Petrol,Automatic,First,0.0,53.140,18.0,Audi,A4,10.50,kmpl,3197.0,CC,NaN,NaN
5919,Hyderabad,2015,8000.0,Petrol,Automatic,First,2.0,69.675,100.0,Jaguar,F,12.50,kmpl,5000.0,CC,488.1,bhp
5294,Delhi,2011,25000.0,Petrol,Automatic,First,2.0,55.070,30.0,BMW,Z4,10.37,kmpl,2979.0,CC,306.0,bhp
5781,Delhi,2011,6500.0,Petrol,Automatic,Third,2.0,11.300,120.0,Lamborghini,Gallardo,6.40,kmpl,5204.0,CC,560.0,bhp
4691,Bangalore,2014,3000.0,Petrol,Automatic,Second,2.0,49.490,90.0,Mercedes-Benz,SLK-Class,12.00,kmpl,5461.0,CC,421.0,bhp

    here we can see that car at index 3999 has 0 seats, we need to impute this value
    we will impute the value by brand and model name which the same car has got

In [29]:
df[(df['Brand'] == 'Audi') & (df['Model'] == 'A4')]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
4,Coimbatore,2013,40670.0,Diesel,Automatic,Second,5.0,53.14,17.74,Audi,A4,15.20,kmpl,1968.0,CC,140.80,bhp
50,Kochi,2015,13648.0,Diesel,Automatic,First,5.0,53.14,21.43,Audi,A4,17.11,kmpl,1968.0,CC,174.33,bhp
65,Jaipur,2012,65664.0,Diesel,Automatic,First,5.0,53.14,13.50,Audi,A4,16.55,kmpl,1968.0,CC,140.00,bhp
103,Kolkata,2010,30000.0,Diesel,Automatic,First,5.0,53.14,9.80,Audi,A4,14.94,kmpl,2967.0,CC,241.40,bhp
150,Coimbatore,2015,48214.0,Diesel,Automatic,First,5.0,53.14,23.32,Audi,A4,17.11,kmpl,1968.0,CC,174.33,bhp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6975,Bangalore,2011,45000.0,Diesel,Automatic,First,5.0,53.14,NaN,Audi,A4,14.94,kmpl,2967.0,CC,241.40,bhp
7023,Bangalore,2014,36000.0,Diesel,Automatic,First,5.0,53.14,NaN,Audi,A4,17.11,kmpl,1968.0,CC,174.33,bhp
7168,Bangalore,2014,65475.0,Diesel,Automatic,First,5.0,53.14,NaN,Audi,A4,16.55,kmpl,1968.0,CC,147.51,bhp
7233,Bangalore,2014,21143.0,Diesel,Automatic,First,5.0,53.14,NaN,Audi,A4,16.55,kmpl,1968.0,CC,147.51,bhp
7238,Hyderabad,2011,64000.0,Diesel,Automatic,First,5.0,53.14,NaN,Audi,A4,16.55,kmpl,1968.0,CC,147.51,bhp

    here we can see that Brand Audi with Model A4 has 5 seats hence we will impute seat as 5 in index 3999

In [30]:
df.loc[3999, 'Seats']=5

In [31]:
df.sort_values(by='mileage_num',ascending=True).head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
7226,Ahmedabad,2014,41000.0,Petrol,Manual,First,5.0,4.55,NaN,Hyundai,Santro,0.0,kmpl,1086.0,CC,62.0,bhp
5647,Mumbai,2001,227000.0,Diesel,Manual,Fourth & Above,8.0,24.01,2.2,Toyota,Qualis,0.0,kmpl,2446.0,CC,NaN,NaN
707,Pune,2014,120000.0,Diesel,Automatic,First,5.0,49.49,30.0,Mercedes-Benz,M-Class,0.0,kmpl,2987.0,CC,165.0,bhp
6697,Jaipur,2007,85000.0,Petrol,Manual,Second,5.0,4.55,NaN,Hyundai,Santro,0.0,kmpl,1086.0,CC,NaN,NaN
6093,Bangalore,2007,47000.0,Petrol,Manual,Second,5.0,4.55,NaN,Hyundai,Santro,0.0,kmpl,1086.0,CC,NaN,NaN

In [32]:
(df['mileage_num'] == 0).sum()

np.int64(81)

    we have 81 values of mileage_num as 0 which we need to impute with NaN

    df.loc[condition, 'col']

In [33]:
df.loc[df['mileage_num']==0, 'mileage_num']=np.nan

In [42]:
df.isna().sum()

Location                0
Year                    0
Kilometers_Driven       1
Fuel_Type               0
Transmission            0
Owner_Type              0
Seats                  53
New_Price               0
Price                1234
Brand                   0
Model                   0
mileage_num            83
mileage_unit            2
engine_num             46
engine_unit            46
power_num             175
power_unit            175
dtype: int64

In [45]:
df.select_dtypes(include=['int64','float64']).columns

Index(['Year', 'Kilometers_Driven', 'Seats', 'New_Price', 'Price',
       'mileage_num', 'engine_num', 'power_num'],
      dtype='object')

In [50]:
s=df[['Year', 'Kilometers_Driven', 'Seats', 'New_Price',
       'mileage_num', 'engine_num', 'power_num']]

Q1=s.quantile(0.25)
Q3=s.quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-(1.5*IQR)
upper_bound=Q3+(1.5*IQR)
lower_outlier=s<lower_bound
upper_outlier=s>upper_bound

In [51]:
print(lower_outlier.sum())

Year                  58
Kilometers_Driven      0
Seats                137
New_Price              0
mileage_num            1
engine_num             0
power_num              0
dtype: int64

In [52]:
print(upper_outlier.sum())

Year                    0
Kilometers_Driven     257
Seats                1015
New_Price            1098
mileage_num            18
engine_num             65
power_num             273
dtype: int64

In [53]:
for i in s:
  lb=lower_bound[i]
  ub=upper_bound[i]
  df[i]=df[i].clip(lower=lb, upper=ub)

In [65]:
df.select_dtypes(include=['float64']).isna().sum()

Year                    0
Kilometers_Driven       1
Seats                  53
New_Price               0
Price                1234
mileage_num            83
engine_num             46
power_num             175
dtype: int64

In [66]:
df.select_dtypes(include=['object']).isna().sum()

Location          0
Fuel_Type         0
Transmission      0
Owner_Type        0
Brand             0
Model             0
mileage_unit      2
engine_unit      46
power_unit      175
dtype: int64

In [69]:
df[df['Seats'].isna()]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
194,Ahmedabad,2007.0,60006.0,Petrol,Manual,First,NaN,13.580,2.95,Honda,City,NaN,kmpl,NaN,NaN,NaN,NaN
208,Kolkata,2010.0,42001.0,Petrol,Manual,First,NaN,7.880,2.11,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
229,Bangalore,2015.0,70436.0,Diesel,Manual,First,NaN,7.650,3.60,Ford,Figo,NaN,kmpl,1498.0,CC,99.0,bhp
733,Chennai,2006.0,97800.0,Petrol,Manual,Third,NaN,7.880,1.75,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
749,Mumbai,2008.0,55001.0,Diesel,Automatic,Second,NaN,42.405,26.50,Land,Rover,NaN,kmpl,NaN,NaN,NaN,NaN
1294,Delhi,2009.0,55005.0,Petrol,Manual,First,NaN,13.580,3.20,Honda,City,12.80,kmpl,NaN,NaN,NaN,NaN
1327,Hyderabad,2015.0,50295.0,Petrol,Manual,First,NaN,7.880,5.80,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
1385,Pune,2004.0,115000.0,Petrol,Manual,Second,NaN,13.580,1.50,Honda,City,NaN,kmpl,NaN,NaN,NaN,NaN
1460,Coimbatore,2008.0,69078.0,Petrol,Manual,First,NaN,42.405,40.88,Land,Rover,NaN,kmpl,NaN,NaN,NaN,NaN
1917,Jaipur,2005.0,88000.0,Petrol,Manual,Second,NaN,13.580,1.70,Honda,City,13.00,kmpl,1493.0,CC,100.0,bhp
2074,Pune,2011.0,24255.0,Petrol,Manual,First,NaN,7.880,3.15,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
2096,Coimbatore,2004.0,52146.0,Petrol,Manual,First,NaN,4.550,1.93,Hyundai,Santro,NaN,kmpl,NaN,NaN,NaN,NaN
2264,Pune,2012.0,24500.0,Petrol,Manual,Second,NaN,8.525,2.95,Toyota,Etios,18.30,kmpl,NaN,NaN,NaN,NaN
2325,Pune,2015.0,67000.0,Petrol,Manual,First,NaN,7.880,4.70,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
2335,Mumbai,2007.0,55000.0,Petrol,Manual,Second,NaN,7.880,1.75,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
2369,Chennai,2008.0,56000.0,Petrol,Manual,Second,NaN,7.880,1.50,Maruti,Estilo,19.50,kmpl,1061.0,CC,NaN,NaN
2530,Kochi,2014.0,64158.0,Diesel,Automatic,First,NaN,42.405,17.89,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
2542,Bangalore,2011.0,65000.0,Petrol,Manual,Second,NaN,4.550,3.15,Hyundai,Santro,NaN,kmpl,NaN,NaN,NaN,NaN
2623,Pune,2012.0,95000.0,Diesel,Automatic,Second,NaN,42.405,18.00,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
2668,Kolkata,2014.0,32986.0,Petrol,Manual,First,NaN,7.880,4.24,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
2737,Jaipur,2003.5,131500.0,Petrol,Manual,First,NaN,5.510,0.70,Maruti,Wagon,12.00,kmpl,NaN,NaN,NaN,NaN
2780,Pune,2009.0,100000.0,Petrol,Manual,First,NaN,4.550,1.60,Hyundai,Santro,NaN,kmpl,NaN,NaN,NaN,NaN
2842,Bangalore,2012.0,43000.0,Petrol,Manual,First,NaN,4.550,3.25,Hyundai,Santro,NaN,kmpl,NaN,NaN,NaN,NaN
3272,Mumbai,2008.0,81000.0,Diesel,Automatic,Second,NaN,42.405,10.50,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
3404,Jaipur,2006.0,125000.0,Petrol,Manual,Fourth & Above,NaN,7.880,2.35,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
3520,Delhi,2012.0,90000.0,Diesel,Automatic,First,NaN,42.405,14.50,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
3522,Kochi,2012.0,66400.0,Petrol,Manual,First,NaN,4.550,2.66,Hyundai,Santro,NaN,kmpl,NaN,NaN,NaN,NaN
3800,Mumbai,2012.0,129000.0,Diesel,Automatic,First,NaN,35.290,7.00,Ford,Endeavour,12.80,kmpl,2953.0,CC,NaN,NaN
3810,Kolkata,2013.0,27000.0,Petrol,Automatic,First,NaN,33.510,11.99,Honda,CR-V,14.00,kmpl,NaN,NaN,NaN,NaN
3882,Kolkata,2010.0,40000.0,Petrol,Manual,Second,NaN,7.880,2.50,Maruti,Estilo,19.50,kmpl,1061.0,CC,NaN,NaN
4011,Pune,2011.0,45271.0,Diesel,Manual,First,NaN,8.600,2.60,Fiat,Punto,20.30,kmpl,NaN,NaN,NaN,NaN
4152,Mumbai,2003.5,75000.0,Diesel,Automatic,Second,NaN,42.405,16.11,Land,Rover,NaN,kmpl,NaN,NaN,NaN,NaN
4229,Bangalore,2005.0,79000.0,Petrol,Manual,Second,NaN,4.550,1.65,Hyundai,Santro,17.00,kmpl,NaN,NaN,NaN,NaN
4577,Delhi,2012.0,72000.0,Diesel,Automatic,Third,NaN,42.405,13.85,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
4604,Pune,2011.0,98000.0,Petrol,Manual,First,NaN,9.600,3.15,Honda,Jazz,16.70,kmpl,NaN,NaN,NaN,NaN
4697,Kochi,2017.0,17941.0,Petrol,Manual,First,NaN,8.600,3.93,Fiat,Punto,15.70,kmpl,NaN,NaN,NaN,NaN
4712,Pune,2003.5,80000.0,Petrol,Manual,Second,NaN,4.550,0.90,Hyundai,Santro,17.00,kmpl,NaN,NaN,NaN,NaN
4952,Kolkata,2010.0,47000.0,Petrol,Manual,First,NaN,8.600,1.49,Fiat,Punto,14.60,kmpl,NaN,NaN,NaN,NaN
5015,Delhi,2006.0,63000.0,Petrol,Manual,First,NaN,7.880,1.60,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
5185,Delhi,2012.0,52000.0,Petrol,Manual,First,NaN,7.880,3.65,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
5270,Bangalore,2003.5,53000.0,Petrol,Manual,Second,NaN,13.580,1.85,Honda,City,NaN,kmpl,NaN,NaN,NaN,NaN
5893,Chennai,2008.0,51000.0,Petrol,Manual,Second,NaN,7.880,1.75,Maruti,Estilo,19.50,kmpl,1061.0,CC,NaN,NaN
6042,Bangalore,2009.0,72000.0,Petrol,Manual,Second,NaN,25.830,NaN,Skoda,Laura,17.50,kmpl,NaN,NaN,NaN,NaN
6541,Bangalore,2012.0,56600.0,Diesel,Manual,First,NaN,8.525,NaN,Toyota,Etios,23.59,kmpl,NaN,NaN,NaN,NaN
6544,Bangalore,2012.0,58000.0,Petrol,Automatic,Second,NaN,10.250,NaN,Hyundai,i20,15.00,kmpl,NaN,NaN,NaN,NaN
6633,Kolkata,2016.0,27000.0,Diesel,Manual,First,NaN,18.865,NaN,Mahindra,TUV,NaN,kmpl,NaN,NaN,NaN,NaN
6643,Bangalore,2009.0,131500.0,Diesel,Automatic,Second,NaN,42.405,NaN,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
6651,Kolkata,2015.0,36009.0,Petrol,Manual,First,NaN,7.880,NaN,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
6677,Jaipur,2010.0,65000.0,Petrol,Manual,Third,NaN,8.600,NaN,Fiat,Punto,14.60,kmpl,NaN,NaN,NaN,NaN
6685,Pune,2010.0,115000.0,Petrol,Manual,Second,NaN,7.880,NaN,Maruti,Swift,16.10,kmpl,NaN,NaN,NaN,NaN
6880,Chennai,2009.0,95000.0,Diesel,Automatic,Second,NaN,42.405,NaN,BMW,5,18.48,kmpl,NaN,NaN,NaN,NaN
6902,Kochi,2012.0,59311.0,Petrol,Manual,First,NaN,8.525,NaN,Toyota,Etios,18.30,kmpl,NaN,NaN,NaN,NaN
6957,Kochi,2019.0,11574.0,Petrol,Manual,First,NaN,9.600,NaN,Honda,Jazz,NaN,kmpl,1199.0,CC,88.7,bhp

In [80]:
# df.groupby(['Brand','Model'])['Seats'].median()
df.groupby(['Brand', 'Model'], as_index=False)['Seats'].median()

          Brand    Model  Seats
0    Ambassador  Classic    5.0
1          Audi       A3    5.0
2          Audi       A4    5.0
3          Audi       A6    5.0
4          Audi       A7    5.0
..          ...      ...    ...
218       Volvo      S60    5.0
219       Volvo      S80    5.0
220       Volvo      V40    5.0
221       Volvo     XC60    5.0
222       Volvo     XC90    5.0

[223 rows x 3 columns]

    .apply() group-wise operation karta hai but result group level pe hota hai (reduced size)
    .transform() bhi group-wise operation karta hai but original DataFrame ke size ka result deta hai

In [91]:
df["Seats"] = df.groupby(["Brand", "Model"])["Seats"].transform(lambda x: x.fillna(x.median()))

    x har group ka 'Seats' column hai
    x.median() us group ke non-NA values ka median calculate karta hai
    x.fillna(x.median()) us group ke NA values ko us group ke median se replace karta hai

    .transform() ensures ki result original DataFrame ke size ke equal hota hai

    ✅ Use .transform() when you want to fill or map values row-by-row
    ❌ Don’t use .apply() if you care about keeping the row structure same

In [92]:
df.isna().sum()

Location                0
Year                    0
Kilometers_Driven       1
Fuel_Type               0
Transmission            0
Owner_Type              0
Seats                   3
New_Price               0
Price                1234
Brand                   0
Model                   0
mileage_num            83
mileage_unit            2
engine_num             46
engine_unit            46
power_num             175
power_unit            175
dtype: int64

In [93]:
df[df['Seats'].isna()]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
2369,Chennai,2008.0,56000.0,Petrol,Manual,Second,NaN,7.88,1.50,Maruti,Estilo,19.5,kmpl,1061.0,CC,NaN,NaN
3882,Kolkata,2010.0,40000.0,Petrol,Manual,Second,NaN,7.88,2.50,Maruti,Estilo,19.5,kmpl,1061.0,CC,NaN,NaN
5893,Chennai,2008.0,51000.0,Petrol,Manual,Second,NaN,7.88,1.75,Maruti,Estilo,19.5,kmpl,1061.0,CC,NaN,NaN

In [102]:
df[(df['Brand'] == 'Maruti')]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
0,Mumbai,2010.0,72000.0,CNG,Manual,First,5.0,5.51,1.75,Maruti,Wagon,26.60,km/kg,998.0,CC,58.16,bhp
3,Chennai,2012.0,87000.0,Diesel,Manual,First,5.0,11.27,6.00,Maruti,Ertiga,20.77,kmpl,1248.0,CC,88.76,bhp
10,Kochi,2018.0,25692.0,Petrol,Manual,First,5.0,10.65,9.95,Maruti,Ciaz,21.56,kmpl,1462.0,CC,103.25,bhp
12,Jaipur,2015.0,64424.0,Diesel,Manual,First,5.0,7.88,5.60,Maruti,Swift,25.20,kmpl,1248.0,CC,74.00,bhp
17,Jaipur,2017.0,25000.0,Diesel,Manual,First,5.0,7.88,5.99,Maruti,Swift,28.40,kmpl,1248.0,CC,74.00,bhp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7210,Jaipur,2017.0,19000.0,Diesel,Manual,First,5.0,11.12,NaN,Maruti,Vitara,24.30,kmpl,1248.0,CC,88.50,bhp
7218,Mumbai,2018.0,3800.0,Diesel,Automatic,First,5.0,12.46,NaN,Maruti,Vitara,24.30,kmpl,1248.0,CC,88.50,bhp
7220,Delhi,2017.0,14300.0,Diesel,Automatic,First,5.0,9.11,NaN,Maruti,Dzire,28.40,kmpl,1248.0,CC,73.75,bhp
7222,Chennai,2015.0,31717.0,Petrol,Automatic,First,5.0,5.87,NaN,Maruti,Celerio,23.10,kmpl,998.0,CC,67.04,bhp
7235,Kochi,2017.0,21380.0,Diesel,Manual,First,5.0,10.57,NaN,Maruti,Vitara,24.30,kmpl,1248.0,CC,88.50,bhp

In [103]:
df.shape

(7253, 17)

In [105]:
df['Seats']=df.groupby(['Brand'])['Seats'].transform(lambda x: x.fillna(x.median()))

0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
7248    5.0
7249    5.0
7250    5.0
7251    5.0
7252    5.0
Name: Seats, Length: 7253, dtype: float64

In [114]:
df[(df['Brand']=='Maruti')]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,Brand,Model,mileage_num,mileage_unit,engine_num,engine_unit,power_num,power_unit
0,Mumbai,2010.0,72000.0,CNG,Manual,First,5.0,5.51,1.75,Maruti,Wagon,26.60,km/kg,998.0,CC,58.16,bhp
3,Chennai,2012.0,87000.0,Diesel,Manual,First,5.0,11.27,6.00,Maruti,Ertiga,20.77,kmpl,1248.0,CC,88.76,bhp
10,Kochi,2018.0,25692.0,Petrol,Manual,First,5.0,10.65,9.95,Maruti,Ciaz,21.56,kmpl,1462.0,CC,103.25,bhp
12,Jaipur,2015.0,64424.0,Diesel,Manual,First,5.0,7.88,5.60,Maruti,Swift,25.20,kmpl,1248.0,CC,74.00,bhp
17,Jaipur,2017.0,25000.0,Diesel,Manual,First,5.0,7.88,5.99,Maruti,Swift,28.40,kmpl,1248.0,CC,74.00,bhp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7210,Jaipur,2017.0,19000.0,Diesel,Manual,First,5.0,11.12,NaN,Maruti,Vitara,24.30,kmpl,1248.0,CC,88.50,bhp
7218,Mumbai,2018.0,3800.0,Diesel,Automatic,First,5.0,12.46,NaN,Maruti,Vitara,24.30,kmpl,1248.0,CC,88.50,bhp
7220,Delhi,2017.0,14300.0,Diesel,Automatic,First,5.0,9.11,NaN,Maruti,Dzire,28.40,kmpl,1248.0,CC,73.75,bhp
7222,Chennai,2015.0,31717.0,Petrol,Automatic,First,5.0,5.87,NaN,Maruti,Celerio,23.10,kmpl,998.0,CC,67.04,bhp
7235,Kochi,2017.0,21380.0,Diesel,Manual,First,5.0,10.57,NaN,Maruti,Vitara,24.30,kmpl,1248.0,CC,88.50,bhp